apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: creature-realms
  labels:
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/part-of: creature-realms
    app.kubernetes.io/component: observability
data:
  elasticsearch.yml: |
    discovery.type: single-node
    xpack.security.enabled: false
    network.host: 0.0.0.0
