apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: creature-realms
  labels:
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/part-of: creature-realms
    app.kubernetes.io/component: observability
spec:
  type: NodePort
  ports:
    - name: http
      port: 9200
      targetPort: 9200
      nodePort: 30200
    - name: transport
      port: 9300
      targetPort: 9300
  selector:
    app.kubernetes.io/name: elasticsearch
