apiVersion: v1
kind: Service
metadata:
  name: world
  namespace: creature-realms
  labels:
    app.kubernetes.io/name: world
    app.kubernetes.io/part-of: creature-realms
    app.kubernetes.io/component: backend
spec:
  selector:
    app.kubernetes.io/name: world
  type: NodePort
  ports:
    - name: http
      port: 8082
      targetPort: 8082
      protocol: TCP
      nodePort: 30082
    - name: tcp
      port: 9090
      targetPort: 9090
      protocol: TCP
      nodePort: 30092
