apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: creature-realms
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: creature-realms
    app.kubernetes.io/component: cache
spec:
  ports:
    - name: tcp
      port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app.kubernetes.io/name: redis
  type: ClusterIP
