apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: creature-realms
  labels:
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/part-of: creature-realms
    app.kubernetes.io/component: observability
spec:
  type: ClusterIP
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318
    - name: prom-exp
      port: 9464
      targetPort: 9464
  selector:
    app.kubernetes.io/name: otel-collector
