apiVersion: v1
kind: ConfigMap
metadata:
  name: users-config
  namespace: creature-realms
  labels:
    app.kubernetes.io/name: users
    app.kubernetes.io/part-of: creature-realms
    app.kubernetes.io/component: backend
data:
  ASPNETCORE_URLS: http://+:8081
  OTEL__Endpoint: http://otel-collector:4318
