apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: creature-realms
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/part-of: creature-realms
    app.kubernetes.io/component: edge
data:
  nginx.conf: |
    worker_processes  1;
    events { worker_connections  1024; }
    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;
      sendfile        on;
      keepalive_timeout  65;
      client_max_body_size 10m;

      upstream auth_upstream {
        server auth:8080;
      }
      upstream users_upstream {
        server users:8081;
      }

      server {
        listen 8080;
        server_name _;

        location /healthz {
          return 200 'ok';
        }

        location ^~ /gateway/auth/ {
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_pass http://auth_upstream/auth/;
        }
        location ^~ /gateway/users/ {
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_pass http://users_upstream/users/;
        }
      }
    }
