apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: creature-realms
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/part-of: creature-realms
    app.kubernetes.io/component: edge
data:
  nginx.conf: |
    worker_processes  1;
    events { worker_connections  1024; }
    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;
      sendfile        on;
      keepalive_timeout  65;
      client_max_body_size 10m;

      upstream auth_upstream {
        server auth:8080;
      }
      upstream idp_upstream {
        server idp:8081;
      }
      upstream directory_upstream {
        server directory:8085;
      }
      

      server {
        listen 8080;
        server_name _;

        location /healthz {
          return 200 'ok';
        }

        location = /gateway/world/regions.json {
          default_type application/json;
          alias /etc/nginx/regions.json;
        }

        location ~ ^/gateway/auth/(.*)$ {
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_pass http://auth_upstream/auth/$1;
        }
        location = /gateway/auth/healthz {
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_pass http://auth_upstream/healthz;
        }
        location ^~ /gateway/auth/swagger/ {
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_pass http://auth_upstream/swagger/;
        }
        location = /gateway/auth/swagger {
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_pass http://auth_upstream/swagger;
        }
        location ~ ^/gateway/idp/(.*)$ {
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_pass http://idp_upstream/idp/$1;
        }
        location = /gateway/idp/healthz {
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_pass http://idp_upstream/healthz;
        }
        location ^~ /gateway/idp/swagger/ {
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_pass http://idp_upstream/swagger/;
        }
        location = /gateway/idp/swagger {
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_pass http://idp_upstream/swagger;
        }
        location ~ ^/gateway/directory/(.*)$ {
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_pass http://directory_upstream/directory/$1;
        }
        
      }
    }

  regions.json: |
    {
      "regions": [
        { "name": "square1", "minX": -9, "maxX": -5, "minY": -9, "maxY": -5, "tcpPort": 9101, "service": "world-square1:9090" },
        { "name": "square2", "minX": -4, "maxX": 0,  "minY": -9, "maxY": -5, "tcpPort": 9102, "service": "world-square2:9090" }
      ]
    }
