apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - postgres/configmap.yaml
  - postgres/secret.yaml
  - postgres/service.yaml
  - postgres/statefulset.yaml
  - postgres/networkpolicy.yaml
  - redis/configmap.yaml
  - redis/service.yaml
  - redis/statefulset.yaml
  - redis/networkpolicy.yaml
  - ../Auth/k8s
  - ../IDP/k8s
  - ../Gateway/k8s
  - ../Directory/k8s
  - elasticsearch
  - kibana
  - elastic-agent
