apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: creature-realms
  labels:
    app.kubernetes.io/name: kibana
    app.kubernetes.io/part-of: creature-realms
    app.kubernetes.io/component: observability
spec:
  type: NodePort
  ports:
    - name: http
      port: 5601
      targetPort: 5601
      nodePort: 30091
  selector:
    app.kubernetes.io/name: kibana
