apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  namespace: creature-realms
  labels:
    app.kubernetes.io/name: promtail
    app.kubernetes.io/part-of: creature-realms
    app.kubernetes.io/component: observability
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: promtail
  template:
    metadata:
      labels:
        app.kubernetes.io/name: promtail
        app.kubernetes.io/part-of: creature-realms
        app.kubernetes.io/component: observability
    spec:
      serviceAccountName: promtail
      containers:
        - name: promtail
          image: grafana/promtail:2.9.3
          args: ["-config.file=/etc/promtail/promtail.yaml"]
          volumeMounts:
            - name: config
              mountPath: /etc/promtail/promtail.yaml
              subPath: promtail.yaml
            - name: varlog
              mountPath: /var/log
            - name: varlibpods
              mountPath: /var/lib/docker/containers
            - name: run
              mountPath: /run/promtail
      volumes:
        - name: config
          configMap:
            name: promtail-config
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibpods
          hostPath:
            path: /var/lib/docker/containers
        - name: run
          emptyDir: {}
