apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  namespace: creature-realms
  labels:
    app.kubernetes.io/name: auth
    app.kubernetes.io/part-of: creature-realms
    app.kubernetes.io/component: backend
data:
  JWT__Issuer: creature-realms
  JWT__Audience: creature-realms-client
  OTEL__Endpoint: http://otel-collector:4318
