apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: creature-realms
  labels:
    app.kubernetes.io/name: auth
    app.kubernetes.io/part-of: creature-realms
    app.kubernetes.io/component: backend
type: Opaque
stringData:
  JWT__Key: change-this-key
  ConnectionStrings__Default: Host=postgres;Port=5432;Database=creature_realms;Username=cro_admin;Password=please-change-me
