apiVersion: v1
kind: ConfigMap
metadata:
  name: directory-regions
  namespace: creature-realms
  labels:
    app.kubernetes.io/name: directory
    app.kubernetes.io/part-of: creature-realms
    app.kubernetes.io/component: backend
data:
  world.regions.json: |
    {
      "namespace": "creature-realms",
      "regions": [
        { "name": "Littleroot", "minX": -9, "maxX": -3, "minY": 4, "maxY": -5 }
      ]
    }
