apiVersion: v1
kind: ConfigMap
metadata:
  name: directory-regions
  namespace: creature-realms
  labels:
    app.kubernetes.io/name: directory
    app.kubernetes.io/part-of: creature-realms
    app.kubernetes.io/component: backend
data:
  world.regions.json: |
    {
      "namespace": "creature-realms",
      "image": "igormendonca/world:latest",
      "basePort": 9100,
      "regions": [
        {
          "name": "square1",
          "minX": -10,
          "maxX": 0,
          "minY": -6,
          "maxY": 4,
          "tcpPort": 9101,
          "neighbors": {
            "east": "square2",
            "west": "",
            "north": "",
            "south": ""
          }
        },
        {
          "name": "square2",
          "minX": 0,
          "maxX": 9,
          "minY": -6,
          "maxY": 4,
          "tcpPort": 9102,
          "neighbors": {
            "east": "",
            "west": "square1",
            "north": "",
            "south": ""
          }
        }
      ]
    }
