apiVersion: v1
kind: ServiceAccount
metadata:
  name: directory-sa
  namespace: creature-realms
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: directory-reader
  namespace: creature-realms
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: directory-reader-binding
  namespace: creature-realms
subjects:
  - kind: ServiceAccount
    name: directory-sa
    namespace: creature-realms
roleRef:
  kind: Role
  name: directory-reader
  apiGroup: rbac.authorization.k8s.io
