apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: creature-realms
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: creature-realms
    app.kubernetes.io/component: database
data:
  POSTGRES_DB: creature_realms
  POSTGRES_USER: cro_admin
