apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: creature-realms
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: creature-realms
    app.kubernetes.io/component: database
type: Opaque
stringData:
  POSTGRES_PASSWORD: please-change-me
