apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: creature-realms
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: creature-realms
    app.kubernetes.io/component: database
spec:
  ports:
    - name: tcp
      port: 5432
      targetPort: 5432
      protocol: TCP
      nodePort: 30432
  selector:
    app.kubernetes.io/name: postgres
  type: NodePort
