apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: creature-realms
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: creature-realms
    app.kubernetes.io/component: observability
spec:
  type: NodePort
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30090
  selector:
    app.kubernetes.io/name: grafana
