apiVersion: v1
kind: Secret
metadata:
  name: idp-secret
  namespace: creature-realms
  labels:
    app.kubernetes.io/name: idp
    app.kubernetes.io/part-of: creature-realms
    app.kubernetes.io/component: backend
type: Opaque
stringData:
  ConnectionStrings__Default: Host=postgres;Port=5432;Database=creature_realms;Username=cro_admin;Password=please-change-me
  JWT__Key: change-this-key-please-32-chars!
