apiVersion: v1
kind: Service
metadata:
  name: idp
  namespace: creature-realms
  labels:
    app.kubernetes.io/name: idp
    app.kubernetes.io/part-of: creature-realms
    app.kubernetes.io/component: backend
spec:
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      protocol: TCP
      nodePort: 30081
  selector:
    app.kubernetes.io/name: idp
  type: NodePort
